#!/bin/bash
echo "Ejecutando main..."
./Main.py blassss --Ice.Config=Main_i.config > salida &
sleep 1

echo "Ejecutando authenticator..."
./Authenticator.py --Ice.Config=Main_i.config & 
sleep 1

echo "Ejecutando Catálogo..."
./Catalogue.py salida